Repository ans-coe/terraform-modules, pull requests merged in 2023-07, with the labels that each got.

#40 Update/issue33 switch bastion to standard
  azure/bastion/README.md
  azure/bastion/variables.tf
Labels: enhancement

#42 Application Gateway Improvements
  azure/application-gateway/advanced/README.md
  azure/application-gateway/advanced/examples/advanced/main.tf
  azure/application-gateway/advanced/files/selfsigned.pfx
  azure/application-gateway/advanced/keyvault.tf
  azure/application-gateway/advanced/locals.tf
  azure/application-gateway/advanced/main.tf
  azure/application-gateway/advanced/outputs.tf
  azure/application-gateway/advanced/variables.tf
Labels: enhancement

#43 no default probe port should be set by us
  azure/application-gateway/advanced/variables.tf
Labels: bug

#44 Fixed condition where host_names is empty list
  azure/application-gateway/advanced/main.tf
Labels: bug

#47 Power Management Module - July 2023 Update
  azure/power-management/README.md
  azure/power-management/examples/basic/README.md
  azure/power-management/examples/basic/main.tf
  azure/power-management/files/ManagePower-AzAksCluster.ps1
  azure/power-management/files/ManagePower-AzVM.ps1
  azure/power-management/files/ManagePower-AzVmss.ps1
  azure/power-management/files/ManagePower-AzWebApp.ps1
  azure/power-management/files/ManagePower-AzWebAppSlot.ps1
  azure/power-management/locals.tf
  azure/power-management/main.tf
  azure/power-management/outputs.tf
  azure/power-management/variables.tf
Labels: bug, enhancement

#41 Update ADO Project Input Types and add Environment Checks
  azuredevops/project/README.md
  azuredevops/project/examples/advanced/README.md
  azuredevops/project/examples/advanced/main.tf
  azuredevops/project/examples/basic/README.md
  azuredevops/project/examples/basic/main.tf
  azuredevops/project/locals.tf
  azuredevops/project/main.tf
  azuredevops/project/outputs.tf
  azuredevops/project/variables.tf
  azuredevops/project/versions.tf
Labels: enhancement

#46 Switched from map to object for Windows Web App
  azure/windows-webapp/.gitignore
  azure/windows-webapp/.terraform-docs.yml
  azure/windows-webapp/.tflint.hcl
  azure/windows-webapp/README.md
  azure/windows-webapp/examples/advanced/.terraform-docs.yml
  azure/windows-webapp/examples/advanced/README.md
  azure/windows-webapp/examples/advanced/main.tf
  azure/windows-webapp/examples/basic/.terraform-docs.yml
  azure/windows-webapp/examples/basic/README.md
  azure/windows-webapp/examples/basic/main.tf
  azure/windows-webapp/examples/logging/.terraform-docs.yml
  azure/windows-webapp/examples/logging/README.md
  azure/windows-webapp/examples/logging/main.tf
  azure/windows-webapp/examples/privatelink/.terraform-docs.yml
  azure/windows-webapp/examples/privatelink/README.md
  azure/windows-webapp/examples/privatelink/main.tf
  azure/windows-webapp/locals.tf
  azure/windows-webapp/main.tf
  azure/windows-webapp/outputs.tf
  azure/windows-webapp/variables.tf
  azure/windows-webapp/versions.tf
Labels: bug

#45 added IP address outputs
  azure/application-gateway/advanced/examples/advanced/main.tf
  azure/application-gateway/advanced/keyvault.tf
  azure/application-gateway/advanced/main.tf
  azure/application-gateway/advanced/outputs.tf
  azure/application-gateway/advanced/variables.tf
Labels: enhancement

#49 fmt and docs
  azure/application-gateway/advanced/README.md
  azure/application-gateway/advanced/main.tf
  azure/application-gateway/advanced/variables.tf
Labels: bug
