Repository ans-coe/terraform-modules, pull requests merged in 2023-03, with the labels that each got.

#9 Azure VM - Add license_type variable to support byol/hybrid licensing
  azure/linux-virtual-machine/README.md
  azure/linux-virtual-machine/main.tf
  azure/linux-virtual-machine/variables.tf
  azure/windows-virtual-machine/README.md
  azure/windows-virtual-machine/main.tf
  azure/windows-virtual-machine/variables.tf
Labels: enhancement

#20 updated refs/heads/main
  azuredevops/pipelines/README.md
  azuredevops/pipelines/variables.tf
Labels: bug

#21 updated vm readme to include accepting images
  azure/linux-virtual-machine/README.md
  azure/windows-virtual-machine/README.md
Labels: documentation

#19 March - App Service and Function App Improvements
  azure/linux-functionapp/README.md
  azure/linux-functionapp/examples/basic/main.tf
  azure/linux-functionapp/locals.tf
  azure/linux-functionapp/main.tf
  azure/linux-functionapp/outputs.tf
  azure/linux-functionapp/variables.tf
  azure/linux-webapp/README.md
  azure/linux-webapp/examples/basic/main.tf
  azure/linux-webapp/locals.tf
  azure/linux-webapp/main.tf
  azure/linux-webapp/outputs.tf
  azure/linux-webapp/variables.tf
Labels: bug, documentation, enhancement
