Repository ans-coe/terraform-modules, pull requests merged in 2023-10, with the labels that each got.

#65 adding option to create bastion resource group
  azure/hub/README.md
  azure/hub/bastion.tf
  azure/hub/examples/advanced/main.tf
  azure/hub/locals.tf
  azure/hub/variables.tf
Labels: enhancement

#64 Fix/appgw backend hostname
  azure/application-gateway/advanced/README.md
  azure/application-gateway/advanced/keyvault.tf
  azure/application-gateway/advanced/main.tf
  azure/application-gateway/advanced/variables.tf
  azure/application-gateway/advanced/versions.tf
Labels: bug, enhancement

#70 Fix/appgw kv perms
  azure/application-gateway/advanced/README.md
  azure/application-gateway/advanced/examples/advanced/README.md
  azure/application-gateway/advanced/examples/advanced/main.tf
  azure/application-gateway/advanced/keyvault.tf
  azure/application-gateway/advanced/main.tf
  azure/application-gateway/advanced/variables.tf
Labels: enhancement

#71 added ability to set public access enabled
  azure/windows-webapp/main.tf
  azure/windows-webapp/variables.tf
Labels: enhancement

#73 AppGW Add Bot Manager Support
  azure/application-gateway/advanced/README.md
  azure/application-gateway/advanced/examples/advanced/README.md
  azure/application-gateway/advanced/examples/advanced/main.tf
  azure/application-gateway/advanced/keyvault.tf
  azure/application-gateway/advanced/main.tf
  azure/application-gateway/advanced/variables.tf
Labels: enhancement

#74 Feature/add/disable bgp route propagation options to spoke mudule
  azure/spoke/README.md
  azure/spoke/examples/basic/main.tf
  azure/spoke/main.tf
  azure/spoke/variables.tf
Labels: enhancement

#77 Fixes to application gateway
  azure/application-gateway/advanced/README.md
  azure/application-gateway/advanced/main.tf
  azure/application-gateway/advanced/outputs.tf
  azure/application-gateway/advanced/variables.tf
Labels: bug

#72 Add AWS CodeDeploy Workflow Pipelines
  aws/codedeploy_workflow/README.md
  aws/codedeploy_workflow/build/.gitignore
  aws/codedeploy_workflow/build/.terraform-docs.yml
  aws/codedeploy_workflow/build/.tflint.hcl
  aws/codedeploy_workflow/build/LICENSE
  aws/codedeploy_workflow/build/README.md
  aws/codedeploy_workflow/build/data.tf
  aws/codedeploy_workflow/build/main.tf
  aws/codedeploy_workflow/build/outputs.tf
  aws/codedeploy_workflow/build/policy_assume_role_codepipeline.tf
  aws/codedeploy_workflow/build/policy_codepipeline_role.tf
  aws/codedeploy_workflow/build/policy_deploy_bucket.tf
  aws/codedeploy_workflow/build/variables.tf
  aws/codedeploy_workflow/build/versions.tf
  aws/codedeploy_workflow/deploy/.gitignore
  aws/codedeploy_workflow/deploy/.terraform-docs.yml
  aws/codedeploy_workflow/deploy/.tflint.hcl
  aws/codedeploy_workflow/deploy/LICENSE
  aws/codedeploy_workflow/deploy/README.md
  aws/codedeploy_workflow/deploy/codedeploy_group.tf
  aws/codedeploy_workflow/deploy/data.tf
  aws/codedeploy_workflow/deploy/main.tf
  aws/codedeploy_workflow/deploy/outputs.tf
  aws/codedeploy_workflow/deploy/policy_assume_role_codedeploy.tf
  aws/codedeploy_workflow/deploy/policy_assume_role_codepipeline.tf
  aws/codedeploy_workflow/deploy/policy_codepipeline_role.tf
  aws/codedeploy_workflow/deploy/variables.tf
  aws/codedeploy_workflow/deploy/versions.tf
  aws/codedeploy_workflow/examples/basic/.gitignore
  aws/codedeploy_workflow/examples/basic/.terraform-docs.yml
  aws/codedeploy_workflow/examples/basic/.tflint.hcl
  aws/codedeploy_workflow/examples/basic/README.md
  aws/codedeploy_workflow/examples/basic/main.tf
  aws/codedeploy_workflow/examples/basic/policy_deployment.tf
  aws/codedeploy_workflow/examples/basic/prerequsites.tf
  aws/codedeploy_workflow/examples/basic/userdata.sh
  aws/kms_key/.gitignore
  aws/kms_key/.terraform-docs.yml
  aws/kms_key/.tflint.hcl
  aws/kms_key/LICENSE
  aws/kms_key/README.md
  aws/kms_key/examples/basic/.terraform-docs.yml
  aws/kms_key/examples/basic/README.md
  aws/kms_key/examples/basic/main.tf
  aws/kms_key/locals.tf
  aws/kms_key/main.tf
  aws/kms_key/outputs.tf
  aws/kms_key/policy_key_share.tf
  aws/kms_key/variables.tf
  aws/kms_key/versions.tf
Labels: enhancement
